language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - hhvm-nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_install:
  - composer self-update

install:
  - composer update --prefer-source $PREFER_LOWEST